### ISSUE TITLE
Clean up DB Context

### ISSUE THREAD

**Issue by rrgahan** [dontpaniclabs/SolutionTemplate#4]

**Comment by twilsman** [comment]
@rrgahan, what's the difference between this and #3?  What are the different resolutions?

I'd love to involve Tarr on this, but his user account doesn't seem to be associated with this repo?

**Comment by rrgahan** [comment]
There could be use cases I don't know about, but we have found that `DatabaseContext` can be greatly simplified to:

```
internal class DatabaseContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(Common.Shared.Config.SqlServerConnectionString);   
        }
    }
}
```

**Comment by tarrball** [comment]
This issue and #3 are related to the same proposed change of simplifying database rollbacks in tests. The test bases can be simplified to rollback using a transaction scope and the result of that is that all the code inside `DatabaseContext` that is there to facilitate rollbacks in tests can be removed.

**Comment by twilsman** [comment]
Is that how you have your current project set up?  Have you made both of these modifications?

**Comment by tarrball** [comment]
@twilsman yes that's how Tenzing and Jet Linx are both set up
